services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: This!sASu8erPa$$word!
      MSSQL_PID: Developer
      MSSQL_USER: SA
    networks:
      - default
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default
  
  migrator:
    build:
      context: .
      dockerfile: BackeryApi/src/BackeryApi.SqlServer.Migrator/Dockerfile
    depends_on:
      - sql
    links:
      - sql
    environment:
      ConnectionStrings__BackeryApi: "Server=sql,1433;User Id=sa;Password=This!sASu8erPa$$word!;TrustServerCertificate=True;"
  
  api:
    build:
      context: .
      dockerfile: BackeryApi/src/BackeryApi/Dockerfile
    depends_on:
      - sql
    networks:
      - default
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__BackeryApi: "Server=sql,1433;User Id=sa;Password=This!sASu8erPa$$word!;TrustServerCertificate=True;"
  
  api-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "api",
        "-app-port",
        "8080",
        "--resources-path",
        "/components",
        "-log-level",
        "debug",
      ]
    volumes:
      - ./components:/components
    depends_on:
      - api
    network_mode: "service:api"

  webapp:
    build:
      context: .
      dockerfile: PosWebApp/src/WebApp/Dockerfile
    ports:
      - "9080:8080"
    depends_on:
      - api
    networks:
      - default

  webapp-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "-app-id",
        "webapp",
        "-app-port",
        "8080",
        "--resources-path",
        "/components",
        "-log-level",
        "debug",
      ]
    volumes:
      - ./components:/components
    depends_on:
      - webapp
    network_mode: "service:webapp"